language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
script:
  - "rake lint"
  - "rake parser_validate"
  - "rake template_verify"
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.7.0"
  - PUPPET_VERSION="~> 3.0.0"
  - PUPPET_VERSION="~> 3.1.0"
  - PUPPET_VERSION="~> 3.2.0"
  - PUPPET_VERSION="~> 3.3.0"
matrix:
  allow_failures:
    - rvm: 2.0.0
gemfile: Gemfile
